image: Visual Studio 2019
version: "{branch}-{build}"

environment:
  PYTHON: "C:\\Python37"
  PY_PYTHON: 3.7-32
  PY_PYTHON3: 3.7-32

clone_depth: 1

init:
 - ps: Set-WinSystemLocale ja-JP
 - ps: Start-Sleep -s 10
 - ps: Restart-Computer
 - ps: Start-Sleep -s 10
 - tzutil /g
 - tzutil /s "Tokyo Standard Time"
 - tzutil /g

install:
 - set PATH=%PATH%;C:\MinGW;C:\MinGW\bin;C:\MinGW\msys\1.0
 - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
 - python --version
 - git submodule update --init --recursive

build_script:
 - python -m venv .venv
 - .venv\scripts\activate
 - pip install -r requirements-dev.txt
 - run_mypy.cmd > __mypy.txt
 - cd jptools
 - build-and-test.cmd
 - make_html.cmd
 - cd ..
- deactivate
 
artifacts:
 - path: __mypy.txt
 - path: jptools\__h1output.txt
 - path: jptools\__h2output.txt
 - path: jptools\__test_log.txt
 - path: jptools\__jpBrailleHarness.t2t
 - path: jptools\jpBrailleHarness.xhtml
