call setenv-x86.cmd
cd ..\include\jtalk
call all-clean.cmd
call all-build.cmd
call all-install.cmd
cd ..\..\jptools
call test-mecab.cmd
cd ..\include\python-jtalk
call clean.cmd
cd ..\..\jptools
